### ISSUE TITLE
Got java.util.ConcurrentModificationException trying install

### ISSUE THREAD

**Issue by eriknyk** [solrudev/Ackpine#70]
I just got the following exception and the app crashed.

```
22:53:38.327  E  FATAL EXCEPTION: ackpine.pool-2
                 Process: com.testline, PID: 25122
                 java.util.ConcurrentModificationException
                 	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:760)
                 	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:782)
                 	at ru.solrudev.ackpine.impl.session.AbstractSession.setState(AbstractSession.kt:91)
                 	at ru.solrudev.ackpine.impl.session.AbstractSession.completeExceptionally(AbstractSession.kt:244)
                 	at ru.solrudev.ackpine.impl.session.AbstractSession.launch$lambda$3(AbstractSession.kt:163)
                 	at ru.solrudev.ackpine.impl.session.AbstractSession.$r8$lambda$r7LANzByLTn5O4ddmFnq5gTMbDA(Unknown Source:0)
                 	at ru.solrudev.ackpine.impl.session.AbstractSession$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
                 	at ru.solrudev.ackpine.helpers.SerialExecutor$Task.run(SerialExecutor.kt:45)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                 	at java.lang.Thread.run(Thread.java:1012)
```

Happened once on my internal dev tests, I have no idea howto reproduce it happened when trying to make a install randomly.
Just wanted to posted here to track it.

**Comment by solrudev** [comment]
Fix was released in 0.7.1.
